#include <nds.h>
#include <stddef.h>
#include <string.h>

#include "BG.h"
#include "Cross.h"
#include "nds/arm9/background.h"

// void setPalette() {
//     BG_PALETTE_SUB[0] = RED;
//     BG_PALETTE_SUB[1] = BLUE;
//     BG_PALETTE_SUB[2] = GREEN;
//     BG_PALETTE_SUB[3] = WHITE;
//     BG_PALETTE_SUB[4] = BLACK;
// }

void setBackground() {
    // 1) VRAM Configuration for MAIN engine
    VRAM_A_CR = VRAM_ENABLE | VRAM_A_MAIN_BG;

    // 2) Main engine configuration in rotoscale mode
    REG_DISPCNT = MODE_5_2D | DISPLAY_BG2_ACTIVE | DISPLAY_BG3_ACTIVE;

    // 3) Configure the background (Ignore warning 'large implictly truncated to unsigned type')
    BGCTRL[2] = BG_BMP_BASE(0) | BgSize_B8_256x256;

    // 4) Copy bitmap and palette generated by grit
    // swiCopy(BGBitmap, BG_BMP_RAM(0), BGBitmapLen/2);
    // memset(BG_BMP_RAM(0), 0, 256*192);
    swiCopy(BGPal, BG_PALETTE, BGPalLen / 2);

    bgTransform[2]->hdx = 1 * 256;
    bgTransform[2]->vdx = 0 * 256;
    bgTransform[2]->hdy = 0 * 256;
    bgTransform[2]->vdy = 1 * 256;
    bgTransform[2]->dx = 0 * 256;
    bgTransform[2]->dy = 0 * 256;
}

void setCross() {
    // 3) Configure the background (Ignore warning 'large implictly truncated to unsigned type')
    BGCTRL[3] = BG_BMP_BASE(5) | BgSize_B8_256x256;

    // BG_BMP_RAM(5)[0] = 1;

    for (size_t i = 0; i < 256 * 192 / 4; i++) {
        u8 first = CrossBitmap[i];
        u8 second = CrossBitmap[i + 1];
        *(BG_BMP_RAM(5) + 2*i) = first >> 16;
        *(BG_BMP_RAM(5) + 2*i + 1) = first & 0xFF;
    }

    // swiCopy(CrossBitmap, BG_BMP_RAM(5) + 30 + 30*256, CrossBitmapLen/2);
    // for (size_t row = 0; row < 40; row++) {
    //     for (size_t col = 0; col < 40 / 2; col++) {
    //         u8 first = CrossBitmap[row * 256 + 2 * col];
    //         BG_BMP_RAM(1)[row * 256/2 + col] =
    //         (first << 8) | CrossBitmap[row * 256 + 2 * col + 1];
    //     }
    // }
    // swiCopy(CrossBitmap, BG_BMP_RAM(0), CrossBitmapLen/2);
    // for (size_t i = 0; i < CrossPalLen; i++) {
    //     ((u8 *) BG_BMP_RAM(0))[i] += 3;
    // }
    // swiCopy(CrossPal, BG_PALETTE + 3, CrossPalLen/2 - 6);

    bgTransform[3]->hdx = 1 * 256;
    bgTransform[3]->vdx = 0 * 256;
    bgTransform[3]->hdy = 0 * 256;
    bgTransform[3]->vdy = 1 * 256;
    bgTransform[3]->dx = 0 * 256;
    bgTransform[3]->dy = 0 * 256;
}
